version: "3.7"

services:
  app:
    image: &app beeracademy/web
    networks:
      - traefik
      - default
    volumes:
      - ./media:/app/media
      - ./static:/app/static
      - ./.env:/app/.env
    labels:
      - traefik.enable=true
      - traefik.http.routers.academy-beer.rule=Host(`academy.beer`)
      - traefik.http.services.academy-beer.loadbalancer.server.port=8000
    depends_on:
      - db
      - media
      - static
      - celery
      - celery-beat
      - redis

  celery:
    image: *app
    command: ["celery", "worker", "--app=academy", "--loglevel=INFO"]
    volumes:
      - ./.env:/app/.env
    depends_on:
      - redis
      - db

  celery-beat:
    image: *app
    command: ["celery", "beat", "--app=academy", "--loglevel=INFO", "--scheduler=django_celery_beat.schedulers:DatabaseScheduler"]
    volumes:
      - ./.env:/app/.env
    depends_on:
      - redis
      - db

  db:
    image: postgres:12
    volumes:
      - ./db_data:/var/lib/postgresql/data

  media:
    image: nginx:alpine
    volumes:
      - ./media:/usr/share/nginx/html
      - ./nginx-default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.media-academy-beer.rule=Host(`media.academy.beer`)
      - traefik.http.services.media-academy-beer.loadbalancer.server.port=80

  static:
    image: nginx:alpine
    volumes:
      - ./static:/usr/share/nginx/html
      - ./nginx-default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.static-academy-beer.rule=Host(`static.academy.beer`)
      - traefik.http.services.static-academy-beer.loadbalancer.server.port=80

  redis:
    image: redis:alpine

networks:
  traefik:
    external: true
