version: "3"

services:
  app:
    build: .
    restart: always
    networks:
      - web
      - default
    expose:
      - "8000"
    labels:
      - "traefik.backend=website"
      - "traefik.frontend.rule=Host:academy.beer"
      - "traefik.port=8000"
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.domain=academy.beer"
    container_name: academy.beer
    depends_on:
      - db

  db:
    image: postgres

networks:
  web:
    external: true
