name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Pull existing images
      run: docker-compose pull

    - name: Restore docker layer cache
      uses: satackey/action-docker-layer-caching@v0.0.8
      continue-on-error: true

    - name: Build image
      run: ./build

    - name: Run tests
      run: docker run --env DJANGO_SETTINGS_MODULE=academy.settings.development beeracademy/web ./manage.py test

    - name: Run tests using postgres
      run: USE_DOCKER=1 ./test_postgres

    - name: Test docker-compose
      run: |
        for k in "SECRET_KEY" "EMAIL_HOST_PASSWORD" "FACEBOOK_ACCESS_TOKEN"; do
          echo "$k=foo" >> ".env"
        done
        docker network create traefik
        docker-compose up -d
        sleep 10
        res=$(docker-compose ps)
        echo "$res"
        if "$res" | grep Exit &>/dev/null; then
          exit 1
        fi

    - name: Publish image to Docker Hub
      run: |
        echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
        docker push beeracademy/web
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    - name: Deploy image to production
      run: curl --fail -X POST "$WEBHOOK_URL"
      env:
        WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
